name: "Test & Release Notes"
on:
  push:
    branches:
      - '*'
  release:
    types:
      - created
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build container (which includes running tests)
        run: docker build .
  # Docker Hub does actual build for release
  release-notes:
    needs: test
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install github-release-notes -g
      - run: gren release --override
        env:
          GREN_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
